import puppeteer from "puppeteer";

/**
 * Generates a PDF ESG Report
 * @param {Object} data - Report data (co2, savings, tenantName)
 * @returns {Buffer} PDF buffer
 */
export async function generateESGReport(data) {
    const browser = await puppeteer.launch({ headless: "new" });
    const page = await browser.newPage();

    const htmlContent = `
    <html>
        <head>
            <style>
                body { font-family: 'Arial', sans-serif; padding: 40px; color: #333; }
                .header { text-align: center; border-bottom: 2px solid #4CAF50; padding-bottom: 20px; }
                .title { color: #2E7D32; font-size: 28px; }
                .section { margin-top: 30px; }
                .stat-box { display: flex; justify-content: space-between; margin-top: 20px; }
                .stat { background: #f1f8e9; padding: 20px; border-radius: 8px; width: 30%; text-align: center; }
                .footer { margin-top: 50px; font-size: 12px; color: #888; text-align: center; }
            </style>
        </head>
        <body>
            <div class="header">
                <h1 class="title">ESG Sustainability Report</h1>
                <p>Tenant: ${data.tenantName}</p>
                <p>Date: ${new Date().toLocaleDateString()}</p>
            </div>
            
            <div class="section">
                <h2>Environmental Impact Summary</h2>
                <div class="stat-box">
                    <div class="stat">
                        <h3>Total CO2</h3>
                        <p>${data.totalCO2} kg</p>
                    </div>
                    <div class="stat">
                        <h3>Reduction</h3>
                        <p>${data.co2Reduction}%</p>
                    </div>
                    <div class="stat">
                        <h3>Green Score</h3>
                        <p>${data.greenScore}/100</p>
                    </div>
                </div>
            </div>

            <div class="section">
                <h2>Cost & Optimization</h2>
                <p>By implementing our ML-driven recommendations, your organization has achieved:</p>
                <ul>
                    <li><strong>Total Cost Savings:</strong> $${data.totalSavings}</li>
                    <li><strong>Idle Resources Terminated:</strong> ${data.idleCount}</li>
                    <li><strong>Efficiency Improvement:</strong> ${data.efficiencyGain}%</li>
                </ul>
            </div>

            <div class="footer">
                Generated by Sustainable Resource Optimizer - Production Ready SaaS
            </div>
        </body>
    </html>
    `;

    await page.setContent(htmlContent);
    const pdfBuffer = await page.pdf({ format: "A4", printBackground: true });
    
    await browser.close();
    return pdfBuffer;
}
